// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AcarsMessageEvent = { reg: string, flight: string, label: string, text: string, };
