// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdsbVelocity = { ground_speed_kt: number, heading_deg: number, vert_rate_fpm: number, };
