// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AdsbPosition } from "./AdsbPosition";
import type { AdsbVelocity } from "./AdsbVelocity";

export type AircraftState = { 
/**
 * 6-char hex ICAO24 address (e.g. "4840D6")
 */
icao24: string, callsign: string | null, position: AdsbPosition | null, velocity: AdsbVelocity | null, 
/**
 * Unix milliseconds since epoch. f64 (not u64) so ts-rs maps to `number`
 * and not `bigint` — same fix as Plan 1's u32 seq fields. f64 has 53 bits
 * of integer precision; sufficient until year ~287000.
 */
last_seen_ms: number, };
