// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AisShipEvent = { mmsi: number, name: string | null, lat: number, lon: number, speed_kt: number, course: number, };
