// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AmTuning = { center_hz: number, lna_gain_db: number, vga_gain_db: number, amp_enabled: boolean, bandwidth_hz: number, };
