// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppId = "nfm_audio" | "adsb_rx" | "pocsag_tx" | "wfm_rx" | "am_rx" | "usb_rx" | "lsb_rx" | "cw_rx" | "rds_rx" | "aprs_rx" | "ais_rx" | "acars_rx" | "pocsag_rx" | "afsk_rx";
