// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AprsPacketEvent = { src: string, dst: string, payload_type: string, lat: number | null, lon: number | null, comment: string, };
