// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AudioFrame = { seq: bigint, 
/**
 * int16 PCM, 48 kHz, mono. 20 ms = 960 samples.
 */
samples: Array<number>, };
