// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PocsagTxStatus = { "kind": "idle" } | { "kind": "armed" } | { "kind": "transmitting", progress_pct: number, } | { "kind": "complete" } | { "kind": "error", message: string, };
