// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PocsagMessageType } from "./PocsagMessageType";

export type PocsagTxParams = { ric: number, function: number, message: string, message_type: PocsagMessageType, baud_rate: number, center_hz: number, vga_gain_db: number, amp_enabled: boolean, };
