// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppId } from "./AppId";
import type { RecordingFormat } from "./RecordingFormat";

export type RecordingMeta = { id: string, app_id: AppId, format: RecordingFormat, path: string, started_unix_ms: number, duration_ms: number, size_bytes: number, 
/**
 * Optional center frequency tagged at start.
 */
center_hz: number | null, };
