// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RecordingStatus = { id: string, elapsed_ms: number, bytes_written: number, };
