// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RegulatoryClass = "passive" | "amateur_only" | "own_devices_only" | "indoor_test_only";
