// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SpectrumFrame = { seq: number, 
/**
 * log-magnitude, 0..255, length == fft_size
 */
bins: Array<number>, center_hz: number, span_hz: number, };
