//! Reusable DSP blocks built on FutureSDR. Hardware- and protocol-agnostic.

pub mod afsk_demod;
pub mod fsk_slicer;
pub mod audio_filter;
pub mod decimation;
pub mod demod_am;
pub mod demod_fm;
pub mod demod_ssb;
pub mod gauss_fsk;
pub mod magnitude;
pub mod ppm;
pub mod preamble;
pub mod resample;
pub mod spectrum;
pub mod stereo_decode;
pub mod manchester;
pub mod ook_envelope;
pub mod pulse_analyze;
pub mod scanner_engine;
pub mod sig_gen;
pub mod tone_detect;
pub mod bpsk_demod;
pub mod afsk_mod;
pub mod cw_keyer;
pub mod fm_mod;
pub mod spectrum_paint;
pub mod ctcss;
pub mod eye_diagram;
